<a href="https://colab.research.google.com/github/dw-shin/numerical_analysis/blob/main/chapter06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Chapter 6. Direct Methods for Solving Linear Systems
## 6.5 Matrix Factorization

### LU Factorization
#### Pseudocode
<img src="https://github.com/dw-shin/numerical_analysis/blob/main/figures/lu1.png?raw=true" width="700"/>
<img src="https://github.com/dw-shin/numerical_analysis/blob/main/figures/lu2.png?raw=true" width="700"/>

### Q1: Write the appropriate code for the 'None' position.

In [ ]:
def lu(A):
    n = None
    L = None
    U = None
    for i in range(n):
        L[i,i] = None

    # Step 1
    U[0,0] = None
    if U[0,0]==0:
        print('Factorization impossible')
        return

    # Step 2
    for i in range(1,n):
        U[0,i] = None
        L[i,0] = None

    # Step 3
    for i in range(1,n-1):
        U[i,i] = None
        if U[i,i] == 0:
            print('Factorization impossible')
            return

        # Step 4
        for j in range(i+1,n):
            U[i,j] = None
            L[j,i] = None

    # Step 5
    U[-1,-1] = None
    return (L, U)

In [ ]:
A = np.array([[1., 1., 0., 3], [2., 1., -1., 1.], [3., -1., -1., 2.], [-1., 2., 3., -1.]])
L, U = lu(A)

In [ ]:
print('L=')
print(L)
print()
print('U=')
print(U)

```
ans

L=
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

U=
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
 ```

Once the matrix factorization is complete,

$$A\boldsymbol{x} = L U \boldsymbol{x} =  \boldsymbol{b} \qquad \Rightarrow \qquad L\boldsymbol{y} = \boldsymbol{b}\quad \text{where}\quad \boldsymbol{y} = U\boldsymbol{x}$$
<br>

Since $L$ is lower triangular, we have $y_1 =
\frac{b_1}{l_{11}}$ and, for each $i = 2, 3, \cdots, n,$

$$y_i = \frac{1}{l_{ii}}\left[b_i - \sum^{i-1}_{j=1} l_{ij}y_j\right]$$
<br>

Back-substitution for solving $U\boldsymbol{x} = \boldsymbol{y}$

$$x_n = \frac{y_n}{u_{nn}} \qquad \text{and} \qquad x_i = \frac{1}{u_{ii}}\left[y_i - \sum_{j = i+1}^n u_{ij} x_j\right]$$

### Q2: Write the appropriate code for the 'None' position.

In [ ]:
def lu_solve(A,b):
    L, U = lu(A)
    x = None
    y = None
    n = None
    y[0] = None
    for i in range(1,n):
        y[i] = None

    x[-1] = None
    for i in reversed(range(0,n-1)):
        x[i] = None
    return x

In [ ]:
b = np.array([8., 7., 14., -7.])
x = lu_solve(A,b)

In [ ]:
print(x)

```
ans

[ 3. -1.  0.  2.]
```

## Reduced Form (Optional)

$$(A)_{ij} = \left\{\begin{array}{rl}
(L)_{ij} &\qquad \text{if}\quad i > j \\
(U)_{ij} &\qquad \text{if}\quad i \le j\end{array}\right.$$

### Q3: Write the appropriate code for the 'None' position.

In [ ]:
def lu_reduced(A):
    n = None

    if A[0,0]==0:
        print('Factorization impossible')
        return

    # Step 2
    for i in range(1,n):
        A[i,0] = None

    # Step 3
    for i in range(1,n-1):
        A[i,i] = None
        if A[i,i] == 0:
            print('Factorization impossible')
            return

        # Step 4
        for j in range(i+1,n):
            A[i,j] = None
            A[j,i] = None

    # Step 5
    A[-1,-1] = None
    return A

In [ ]:
B = lu_reduced(A)

In [ ]:
print('B =')
print(B)

```
ans

B =
[[  1.   1.   0.   3.]
 [  2.  -1.  -1.  -5.]
 [  3.   4.   3.  13.]
 [ -1.  -3.   0. -13.]]
 ```

### Q4: Write the appropriate code for the 'None' position.

In [ ]:
def lu_solve_reduced(A,b):
    A = lu_reduced(A)
    n = None
    for i in range(1,n):
        b[i] = None

    b[-1] = None
    for i in reversed(range(0,n-1)):
        b[i] = None
    return b

In [ ]:
A = np.array([[1., 1., 0., 3], [2., 1., -1., 1.], [3., -1., -1., 2.], [-1., 2., 3., -1.]])
b = np.array([8., 7., 14., -7.])
x = lu_solve_reduced(A,b)

In [ ]:
print(x)

```
ans

[ 3. -1.  0.  2.]
```