<a href="https://colab.research.google.com/github/dw-shin/numerical_analysis/blob/main/chapter07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Chapter 7. Iterative Techniques in Matrix Algebra
## 7.3 The Jacobi and Gauss-Siedel Iterative Techniques

### Jacobi Iterative Technique
#### Pseudocode
<img src="https://github.com/dw-shin/numerical_analysis/blob/main/figures/jacobi.png?raw=true" width="700"/>

### Q1: Write the appropriate code for the 'None' position.

In [ ]:
def jacobi(A,b,x0,n_iter, Tol):
    n = None
    k = None
    while k <= n_iter:
        x = np.zeros_like(b)
        for i in range(n):
            for j in range(n):
                if j != i:
                    x[i] -= None
            x[i] += None
            x[i] /= None
        print(np.round(x,4))
        if np.max(np.abs(x - x0))/np.max(np.abs(x)) < Tol:
            return x
        k += 1
        x0 = None
    print('Maximum number of iterations exceeded')
    return x

### Example 1
The linear system $A\boldsymbol{x} = \boldsymbol{b}$ given by

$$\begin{array}{rl}
	10 x_1 - x_2 + 2x_3 &= 6 \\
	-x_1 + 11 x_2 - x_3 + 3x_4 &= 25\\
	2 x_1 - x_2 + 10 x_3 - x_4 &= -11 \\
	3 x_2 - x_3 + 8 x_4 &= 15
\end{array}$$

has the unique solution $\boldsymbol{x} = (1,2,-1,1)^t$. Use Jacobi's iterative technique to find approximations $\boldsymbol{x}^{(k)}$ to $\boldsymbol{x}$ starting with $\boldsymbol{x}^{(0)} = (0,0,0,0)^t$ until

$$\frac{\|\boldsymbol{x}^{(k)} - \boldsymbol{x}^{(k-1)}\|_\infty}{\|\boldsymbol{x}^{(k)}\|_\infty} < 10^{-3}$$

In [ ]:
A = np.array([[10.,-1.,2.,0.],[-1.,11.,-1.,3.],[2.,-1.,10.,-1.],[0.,3.,-1.,8.]])
b = np.array([6.,25.,-11.,15.])
n_iter = 10
Tol = 1e-3
x0 = np.zeros(4)

x = jacobi(A,b,x0,n_iter,Tol)

```
ans

[ 0.6     2.2727 -1.1     1.875 ]
[ 1.0473  1.7159 -0.8052  0.8852]
[ 0.9326  2.0533 -1.0493  1.1309]
[ 1.0152  1.9537 -0.9681  0.9738]
[ 0.989   2.0114 -1.0103  1.0214]
[ 1.0032  1.9922 -0.9945  0.9944]
[ 0.9981  2.0023 -1.002   1.0036]
[ 1.0006  1.9987 -0.999   0.9989]
[ 0.9997  2.0004 -1.0004  1.0006]
```

### Matrix Form

\begin{align*}
	A &= \left[\begin{array}{cccc}
		a_{11} & a_{12} & \cdots & a_{1n} \\
		a_{21} & a_{22} & \cdots & a_{2n} \\
		\vdots & \vdots & \ddots & \vdots \\
		a_{n1} & a_{n2} & \cdots & a_{nn}
	\end{array}\right] \\[2ex]
	&= \underbrace{\left[\begin{array}{cccc}
		a_{11} & 0 & \cdots & 0 \\
		0 & a_{22} & \ddots & \vdots \\
		\vdots & \ddots & \ddots & 0 \\
		0 & \cdots & 0 & a_{nn}
	\end{array}\right]}_{D} - \underbrace{\left[\begin{array}{cccc}
		0 & \cdots & \cdots & 0 \\
		-a_{21} & \ddots &  & \vdots \\
		\vdots & \ddots & \ddots & \vdots \\
		-a_{n1} & \cdots & -a_{n,n-1} & 0
	\end{array}\right]}_L - \underbrace{\left[\begin{array}{cccc}
		0 & -a_{12} & \cdots & -a_{1n} \\
		\vdots & \ddots & \ddots & \vdots \\
		\vdots &  & \ddots & -a_{n-1,n} \\
		0 & \cdots & \cdots & 0
	\end{array}\right]}_{U}
\end{align*}

The results in the matrix form of the Jacobi iterative technique:

$$\boldsymbol{x}^{(k)} = D^{-1}(L + U)\boldsymbol{x}^{(k-1)} + D^{-1}\boldsymbol{b},\qquad k = 1,2,\cdots$$

Introducing the notation $T_j = D^{-1}(L+U)$ and $\boldsymbol{c}_j = D^{-1}\boldsymbol{b}$ gives

$$\boldsymbol{x}^{(k)} = T_j \boldsymbol{x}^{(k-1)} + \boldsymbol{c}_j$$

### Example 2
Express the Jacobi iteration method for the linear system $A\boldsymbol{x} = \boldsymbol{b}$ given by

$$\begin{array}{lrl}
	E_1: & 10 x_1 - x_2 + 2x_3 &= 6 \\
	E_2: &-x_1 + 11 x_2 - x_3 + 3x_4 &= 25\\
	E_3: & 2 x_1 - x_2 + 10 x_3 - x_4 &= -11 \\
	E_4: & 3 x_2 - x_3 + 8 x_4 &= 15
\end{array}$$

in the form $\boldsymbol{x}^{(k)} = T\boldsymbol{x}^{(k-1)} + \boldsymbol{c}$.

In [ ]:
A = np.array([[10.,-1.,2.,0.],[-1.,11.,-1.,3.],[2.,-1.,10.,-1.],[0.,3.,-1.,8.]])
b = np.array([6.,25.,-11.,15.])

T = np.array([-A[i]/A[i,i] for i in range(A.shape[0])])
c = b.copy()
for i in range(T.shape[0]):
    c[i] /= A[i,i]
    T[i,i] = 0
print('T=', T)
print('c=',c)

In [ ]:
x0 = np.zeros_like(b)
n_iter = 10
for j in range(n_iter):
    x0 = np.matmul(T,x0) + c
    print(np.round(x0,4))

### Gauss-Seidel Iterative Technique
#### Pseudocode
<img src="https://github.com/dw-shin/numerical_analysis/blob/main/figures/gauss-seidel.png?raw=true" width="700"/>

### Q2: Write the appropriate code for the 'None' position.

In [ ]:
def gauss_seidel(A,b,x0,n_iter, Tol):
    n = None
    k = None
    while k <= n_iter:
        x = np.zeros_like(b)
        for i in range(n):
            for j in range(n):
                if j < i:
                    x[i] -= None
                elif j > i:
                    x[i] -= None
            x[i] += None
            x[i] /= None
        print(np.round(x,4))
        if np.max(np.abs(x - x0))/np.max(np.abs(x)) < Tol:
            return x
        k += 1
        x0 = None
    print('Maximum number of iterations exceeded')
    return x

### Example 3
Use the Gauss-Seidel iterative technique to find approximate solutions to

$$\begin{array}{rl}
	10 x_1 - x_2 + 2x_3 &= 6 \\
	-x_1 + 11 x_2 - x_3 + 3x_4 &= 25\\
	2 x_1 - x_2 + 10 x_3 - x_4 &= -11 \\
	3 x_2 - x_3 + 8 x_4 &= 15
\end{array}$$

starting with $\boldsymbol{x} = (0,0,0,0)^t$ and iterating until

$$\frac{\|\boldsymbol{x}^{(k)} -\boldsymbol{x}^{(k-1)}\|_\infty}{\|\boldsymbol{x}^{(k)}\|_\infty} < 10^{-3}.$$

In [ ]:
A = np.array([[10.,-1.,2.,0.],[-1.,11.,-1.,3.],[2.,-1.,10.,-1.],[0.,3.,-1.,8.]])
b = np.array([6.,25.,-11.,15.])
n_iter = 10
Tol = 1e-3
x0 = np.zeros(4)

x = gauss_seidel(A,b,x0,n_iter,Tol)

```
ans

[ 0.6     2.3273 -0.9873  0.8789]
[ 1.0302  2.0369 -1.0145  0.9843]
[ 1.0066  2.0036 -1.0025  0.9984]
[ 1.0009  2.0003 -1.0003  0.9998]
[ 1.0001  2.     -1.      1.    ]
```

### Matrix Form

$$\boldsymbol{x}^{(k)} = (D-L)^{-1}U\boldsymbol{x}^{(k-1)} + (D-L)^{-1}\boldsymbol{b}$$

Letting $T_g = (D-L)^{-1}U$ and $\boldsymbol{c}_g = (D-L)^{-1}\boldsymbol{b}$, gives the Gauss-Seidel technique the form

$$\boldsymbol{x}^{(k)} = T_g \boldsymbol{x}^{(k-1)} + \boldsymbol{c}_g$$

In [ ]:
A = np.array([[10.,-1.,2.,0.],[-1.,11.,-1.,3.],[2.,-1.,10.,-1.],[0.,3.,-1.,8.]])
b = np.array([6.,25.,-11.,15.])

L = np.zeros_like(A)
D = np.zeros_like(A)
U = np.zeros_like(A)

for i in range(A.shape[0]):
    D[i,i] = A[i,i]
    for j in range(A.shape[0]):
        if i > j:
            L[i,j] = -A[i,j]
        if i < j:
            U[i,j] = -A[i,j]

print('D = ',D)
print('L = ',L)
print('U = ',U)

In [ ]:
T = np.matmul(np.linalg.inv(D-L),U)
c = np.linalg.solve((D-L),b)

print('T = ', T)
print('c = ', c)

In [ ]:
x0 = np.zeros_like(b)
n_iter = 5
for j in range(n_iter):
    x0 = np.matmul(T,x0) + c
    print(np.round(x0,4))